-- 1. BORRAMOS LOS REGISTROS ACTUALES PARA EVITAR DUPLICADOS
TRUNCATE TABLE inventario RESTART IDENTITY;

-- 2. ASEGURAMOS QUE LA CANTIDAD ACEPTE DECIMALES
ALTER TABLE inventario ALTER COLUMN cantidad TYPE NUMERIC(10,2);

-- 3. INSERTAMOS TODO EL INVENTARIO LIMPIO
INSERT INTO inventario (modelo, descripcion, medida, id_udm, id_marca, id_almacen, fila, id_condicion, stock_minimo, cantidad, precio_unitario)
SELECT 
  v.modelo, v.descripcion, v.medida,
  (SELECT id FROM inventario_udm WHERE nombre = v.udm LIMIT 1),
  (SELECT id FROM inventario_marcas WHERE nombre = v.marca LIMIT 1),
  (SELECT id FROM inventario_almacenes WHERE nombre = v.almacen LIMIT 1),
  v.fila,
  (SELECT id FROM inventario_condiciones WHERE nombre = v.condicion LIMIT 1),
  v.stock_min::INTEGER,
  v.cantidad::NUMERIC(10,2),
  v.precio::NUMERIC(10,2)
FROM (VALUES
  ('L6154', 'Carretes Aceite', '', 'Pieza', 'WINTEK', 'ESACLERA', '', 'NUEVO', '1', '6', '4982'),
  ('L6153', 'Carretes Aire', '', 'Pieza', 'WINTEK', 'ESCALERA', '', 'NUEVO', '1', '4', '4516'),
  ('-', 'Recibidor de aceite', '', 'Pieza', 'VEVOR', 'ESTANTE 1', '', 'NUEVO', '1', '1', '5000'),
  ('L1002', 'Recibidor de aceite', '', 'Pieza', 'WINTEK', 'ESTANTE 1', '', 'NUEVO', '1', '1', '3720'),
  ('-', 'Carrete', '', 'Pieza', 'RAASM', 'ESTANTE 1', '1', 'USADO', '1', '1', '0'),
  ('-', 'Carrete', '', 'Pieza', 'WINTEK', 'ESTANTE 1', '1', 'USADO', '1', '1', '0'),
  ('-', 'Carrete sin manguera', '', 'Pieza', 'WINTEK', 'ESTANTE 1', '1', 'USADO', '1', '1', '0'),
  ('F16435000', 'Conector Espiga UREA', '', 'Pieza', 'PIUSI', 'ESTANTE 1', '2', 'NUEVO', '1', '8', '134'),
  ('F16433000', 'Conector Codo Bomba', '', 'Pieza', 'PIUSI', 'ESTANTE 1', '2', 'NUEVO', '1', '4', '204.42'),
  ('F00984200', 'Pistola Cuenta Litros K400', '', 'Pieza', 'PIUSI', 'ESTANTE 1', '2', 'NUEVO', '1', '5', '4934'),
  ('F0037553A', 'Conjunto Diesel EX50', '', 'Pieza', 'PIUSI', 'ESTANTE 1', '2', 'NUEVO', '1', '2', '12901'),
  ('F0077900', 'Pistola Easy View 2.0', '', 'Pieza', 'PIUSI', 'ESTANTE 1', '2', 'NUEVO', '1', '1', '5208'),
  ('Cubeta Bomba, plato,tapa, pistola', 'Conjunto Grasa Pail GREASE', '', 'Pieza', 'PIUSI', 'ESTANTE 1', '2', 'NUEVO', '1', '0', '0'),
  ('F00407340', 'Medidor Digital K24', '', 'Pieza', 'PIUSI', 'ESTANTE 1', '2', 'NUEVO', '1', '3', '3420'),
  ('F0057000A', 'Medidor Diesel K33', '', 'Pieza', 'PIUSI', 'ESTANTE 1', '2', 'NUEVO', '1', '2', '2740'),
  ('F00214N00', 'Bomba Neum�tica  P3.5:1 Aceite', '', 'Pieza', 'PIUSI', 'ESTANTE 1', '2', 'NUEVO', '1', '4', '4415'),
  ('F15176000', '"NIPLE 1"" A 1"" PARA UREA"', '', 'Pieza', 'PIUSI', 'ESTANTE 1', '2', 'NUEVO', '1', '6', '176.22'),
  ('F00611D30', 'Filtro  de urea', '', 'Pieza', 'PIUSI', 'ESTANTE 1', '2', 'NUEVO', '1', '1', '2396'),
  ('F0044601B', 'Valvula GPV 2.0', '', 'Pieza', 'PIUSI', 'ESTANTE 1', '2', 'NUEVO', '1', '1', '15929'),
  ('-', 'Valvulas GPV USADAS', '', 'Pieza', 'PIUSI', 'ESTANTE 1', '', 'USADO', '1', '1', '0'),
  ('-', 'Valvulas GPV DA�ADAS', '', 'Pieza', 'PIUSI', 'ESTANTE 1', '', 'DA�ADO', '1', '4', '0'),
  ('F0020310H', 'Bomba electrica diafragma  MA180', '', 'Pieza', 'PIUSI', 'ESTANTE 1', '2', 'NUEVO', '1', '2', '6783'),
  ('F00973150', 'Pistola Cuenta Litros K40 mecanica', '', 'Pieza', 'PIUSI', 'ESTANTE 1', '2', 'NUEVO', '1', '1', '4900'),
  ('F0061903', 'Pistola UREA A60', '', 'Pieza', 'PIUSI', 'ESTANTE 1', '2', 'NUEVO', '1', '3', '5692'),
  ('Topes para carrete', 'Topes de carrete', '', 'Pieza', 'MILAS', 'ESTANTE 1', '3', 'USADO', '1', '6', '0'),
  ('F00984260', 'Pistola Sin cuenta litros (sin boquilla) K400', '', 'Pieza', 'PIUSI', 'ESTANTE 1', '2', 'NUEVO', '1', '1', '4934'),
  ('L1023', 'Bomba diafragma para aceite L1023', '', 'Pieza', 'WINTEK', 'ESTANTE 1', '4', 'NUEVO', '1', '0', '8239'),
  ('L3723', 'Bomba diafragma para urea', '', 'Pieza', 'WINTEK', 'ESTANTE 1', '4', 'NUEVO', '1', '1', '8117'),
  ('L4250', '"FRL 1/2"" "', '"1/2"""', 'Pieza', 'WINTEK', 'ESTANTE 1', '4', 'NUEVO', '1', '2', '946'),
  ('Para aceite 353120  3:1', 'Bomba Aceite 3:1  353120', '', 'Pieza', 'Samson', 'ESTANTE 1', '4', 'NUEVO', '1', '0', '9492'),
  ('K225-AM', 'Caja con piezas Samson (KIT VALVULE AIR)', '', 'Pieza', 'Samson', 'ESTANTE 1', '3', 'NUEVO', '1', '2', '0'),
  ('-', 'Seal Ring 20/25', '', 'Pieza', 'Samson', 'ESTANTE 1', '3', 'NUEVO', '1', '2', '0'),
  ('-', 'Gasket 20/25', '', 'Pieza', 'Samson', 'ESTANTE 1', '3', 'NUEVO', '1', '2', '0'),
  ('-', 'CUSHION 20/25', '', 'Pieza', 'Samson', 'ESTANTE 1', '3', 'NUEVO', '1', '2', '0'),
  ('-', 'BALL 25N 90 DUF', '', 'Pieza', 'Samson', 'ESTANTE 1', '3', 'NUEVO', '1', '1', '0'),
  ('-', 'PILOT VALVE ASSY 20/25', '', 'Pieza', 'Samson', 'ESTANTE 1', '3', 'NUEVO', '1', '2', '0'),
  ('-', 'GK4', '', 'Pieza', 'Samson', 'ESTANTE 1', '3', 'NUEVO', '1', '4', '0'),
  ('-', 'GK2', '', 'Pieza', 'Samson', 'ESTANTE 1', '3', 'NUEVO', '1', '4', '0'),
  ('-', 'CUSHION 20/25', '', 'Pieza', 'Samson', 'ESTANTE 1', '3', 'NUEVO', '1', '2', '0'),
  ('-', 'V-PACKING 20/25', '', 'Pieza', 'Samson', 'ESTANTE 1', '3', 'NUEVO', '1', '2', '0'),
  ('-', 'PACKING 20/25', '', 'Pieza', 'Samson', 'ESTANTE 1', '3', 'NUEVO', '1', '2', '0'),
  ('-', 'ORING 23.47 MM X 2.62 MM', '', 'Pieza', 'Samson', 'ESTANTE 1', '3', 'NUEVO', '1', '2', '0'),
  ('-', 'THROAT BEARING 20/25', '', 'Pieza', 'Samson', 'ESTANTE 1', '3', 'NUEVO', '1', '2', '0'),
  ('-', 'Gasket 20/25', '', 'Pieza', 'Samson', 'ESTANTE 1', '3', 'NUEVO', '1', '2', '0'),
  ('-', 'Gasket 20/25', '', 'Pieza', 'Samson', 'ESTANTE 1', '3', 'NUEVO', '1', '2', '0'),
  ('-', 'SPRING 20/25', '', 'Pieza', 'Samson', 'ESTANTE 1', '3', 'NUEVO', '1', '2', '0'),
  ('-', 'PILOT VALVE SEAT 20/25', '', 'Pieza', 'Samson', 'ESTANTE 1', '3', 'NUEVO', '1', '2', '0'),
  ('-', 'ORING 23.3 MM X 2.4 MM', '', 'Pieza', 'Samson', 'ESTANTE 1', '3', 'NUEVO', '1', '2', '0'),
  ('-', 'ORING 44.5 MM X 3 MM', '', 'Pieza', 'Samson', 'ESTANTE 1', '3', 'NUEVO', '1', '1', '0'),
  ('-', 'ORING 46 MM X 3.5 MM', '', 'Pieza', 'Samson', 'ESTANTE 1', '3', 'NUEVO', '1', '1', '0'),
  ('-', '"HOSE STOP 1/2"" ID"', '', 'Pieza', 'Samson', 'ESTANTE 1', '3', 'NUEVO', '1', '2', '0'),
  ('-', 'GKS', '', 'Pieza', 'Samson', 'ESTANTE 1', '3', 'NUEVO', '1', '4', '0'),
  ('-', 'ORING 11 MM X 2.5 MM', '', 'Pieza', 'Samson', 'ESTANTE 1', '3', 'NUEVO', '1', '2', '0'),
  ('-', 'ORING 7.5 MM X 2 MM', '', 'Pieza', 'Samson', 'ESTANTE 1', '3', 'NUEVO', '1', '2', '0'),
  ('-', 'AK3', '', 'Pieza', 'Samson', 'ESTANTE 1', '3', 'NUEVO', '1', '4', '0'),
  ('-', 'INLET FILTER KIT', '', 'Pieza', 'Samson', 'ESTANTE 1', '3', 'NUEVO', '1', '3', '0'),
  ('-', 'PM2 AIR MOTOR', '', 'Pieza', 'Samson', 'ESTANTE 1', '3', 'NUEVO', '1', '1', '0'),
  ('-', '3:1 PACKING REPAIR KIT', '', 'Pieza', 'Samson', 'ESTANTE 1', '3', 'NUEVO', '1', '1', '0'),
  ('-', 'KIT 2 DIAFRAGMAS', '', 'Pieza', 'Samson', 'ESTANTE 1', '3', 'NUEVO', '1', '1', '0'),
  ('-', 'CILINDRO MOTOR BOMBA ACEITE', '', 'Pieza', 'Samson', 'ESTANTE 1', '3', 'NUEVO', '1', '1', '0'),
  ('Regulador de voltaje', 'Regulador', '', 'Pieza', 'Koblenz', 'ESTANTE 1', '3', 'NUEVO', '1', '0', '600'),
  ('FRL-FR015', 'Filtro Regulador 1/4', '"1/4"""', 'Pieza', 'Weston', 'ESTANTE 1', '3', 'NUEVO', '1', '4', '354'),
  ('Graco', 'Pistola de Alto Flujo Graco', '', 'Pieza', 'Graco', 'ESTANTE 1', '3', 'USADO', '1', '1', '0'),
  ('CAT5E-100', 'Cable UTP', '', 'METRO', 'STEREN', 'ESTANTE 1', '3', 'USADO', '1', '0', '900'),
  ('207385', 'KIT GRACO bomba 3:1', '', 'PIEZA', 'Graco', 'ESTANTE 1', '3', 'NUEVO', '1', '1', '0'),
  ('204-164', 'KIT GRACO', '', 'PIEZA', 'Graco', 'ESTANTE 1', '3', 'NUEVO', '1', '1', '0'),
  ('2644', 'VALVULA ANTIRETORNO', '"4"""', 'PIEZA', 'FLEXIMATIC', 'ESTANTE 1', '3', 'USADO', '1', '1', '0'),
  ('-', 'TAPAS PARA TOTE DE 1000', '', 'PIEZA', 'MILAS', 'ESTANTE 1', '3', 'NUEVO', '1', '7', '0'),
  ('-', 'TAPAS PARA TOTE DE 1000 ARMADAS', '', 'PIEZA', 'MILAS', 'ESTANTE 1', '3', 'NUEVO', '1', '3', '0'),
  ('-', 'Pistola Sin cuenta litros', '', 'PIEZA', 'Genérico', 'ESTANTE 1', '4', 'USADO', '1', '1', '0'),
  ('-', 'Boquilla automatica', '', 'PIEZA', 'Genérico', 'ESTANTE 1', '4', 'USADO', '1', '1', '0'),
  ('-', 'Valvula Solenoide', '', 'PIEZA', 'Cematic', 'ESTANTE 1', '4', 'USADO', '1', '1', '0'),
  ('GL-1-2', 'INYECTOR TIPO BOTELLA', '', 'PIEZA', 'Graco', 'ESTANTE 1', '4', 'USADO', '1', '1', '0'),
  ('GL-1', 'INYECTOR', '', 'PIEZA', 'Genérico', 'ESTANTE 1', '4', 'NUEVO', '1', '1', '0'),
  ('-', 'KIT LINCON', '', 'PIEZA', 'Genérico', 'ESTANTE 1', '4', 'USADO', '1', '0', '0'),
  ('L1710', 'BOMBA MANUAL ROTATIVA DIESEL/ ACEITE', '', 'PIEZA', 'WINTEK', 'ESTANTE 1', '4', 'NUEVO', '1', '2', '950'),
  ('L1803', 'PISTOLA DIGITAL CUENTA LITROS BOQUILLA AUTOMATICA', '', 'PIEZA', 'WINTEK', 'ESTANTE 1', '4', 'NUEVO', '1', '3', '1892'),
  ('B331107', 'Swivel Z', '"1/4"""', 'PIEZA', 'Alemite', 'ESTANTE 1', '4', 'NUEVO', '1', '2', '0'),
  ('Medidor digital chino (caja blanca)', 'Medidor Digital Chino', '', 'PIEZA', 'Chino', 'ESTANTE 1', '4', 'USADO', '1', '3', '0'),
  ('F00808P10', 'Bomba de Diafragma', '', 'PIEZA', 'PIUSI', 'ESTANTE 1', '3', 'NUEVO', '1', '1', '7322'),
  ('Base de metal', 'Base ancha Bomba y Carrete', '', 'PIEZA', 'MILAS', 'ESTANTE 1', '5', 'NUEVO', '1', '0', '1100'),
  ('Base de metal', 'Base delgada Bomba', '', 'PIEZA', 'MILAS', 'ESTANTE 1', '5', 'NUEVO', '1', '4', '800'),
  ('A200', 'Conector R�pido  A200  Polipropileno Cuerda Normal', '"2"""', 'PIEZA', 'Genérico', 'ESTANTE 2', '', 'NUEVO', '1', '15', '0'),
  ('A200', 'Conector R�pido  A200  Aluminio Cuerda Normal', '"2"""', 'PIEZA', 'Genérico', 'ESTANTE 2', '', 'NUEVO', '1', '1', '0'),
  ('A200', 'Conector R�pido  A200 Polipropileno Cuerda Ancha', '"2"""', 'PIEZA', 'Genérico', 'ESTANTE 2', '', 'NUEVO', '1', '7', '191'),
  ('F200', 'Conector R�pido  F200 Polipropileno', '"2"""', 'PIEZA', 'Genérico', 'ESTANTE 2', '', 'NUEVO', '1', '0', '0'),
  ('DC200', 'Conector R�pido DC200 Polipropileno', '"2"""', 'PIEZA', 'Genérico', 'ESTANTE 2', '', 'NUEVO', '1', '0', '0'),
  ('DC200', 'Conector R�pido DC200 Aluminio', '"2"""', 'PIEZA', 'Genérico', 'ESTANTE 2', '', 'NUEVO', '1', '1', '0'),
  ('D200', 'Conector R�pido D200 Polipropileno', '"2"""', 'PIEZA', 'Genérico', 'ESTANTE 2', '', 'NUEVO', '1', '18', '0'),
  ('B200', 'Conector Rapido B200 Aluminio', '"2"""', 'PIEZA', 'Genérico', 'ESTANTE 2', '', 'NUEVO', '1', '1', '0'),
  ('B200', 'Conector R�pido B200 Polipropileno', '"2"""', 'PIEZA', 'Genérico', 'ESTANTE 2', '', 'NUEVO', '1', '8', '0'),
  ('DP100', 'Tap�n DP Polipropileno', '"1"""', 'PIEZA', 'Genérico', 'ESTANTE 2', '', 'NUEVO', '1', '1', '0'),
  ('C100', 'Conector R�pido C100 Polipropileno', '"1"""', 'PIEZA', 'Genérico', 'ESTANTE 2', '', 'NUEVO', '1', '2', '0'),
  ('F100', 'Conector R�pido F100 Polipropileno', '"1"""', 'PIEZA', 'Genérico', 'ESTANTE 2', '', 'NUEVO', '1', '5', '0'),
  ('DC100', 'Conector R�pido DC100 Polipropileno', '"1"""', 'PIEZA', 'Genérico', 'ESTANTE 2', '', 'NUEVO', '1', '0', '0'),
  ('D075', 'Conector R�pido D075 Polipropileno', '"3/4"""', 'PIEZA', 'Genérico', 'ESTANTE 2', '', 'NUEVO', '1', '1', '0'),
  ('C150', 'Conector R�pido C150 Aluminio', '"1 1/2"""', 'PIEZA', 'Genérico', 'ESTANTE 2', '', 'NUEVO', '1', '1', '0'),
  ('-', 'COLPLES ROSCADOS PVC C80', '"2"""', 'PIEZA', 'Genérico', 'ESTANTE 2', '', 'NUEVO', '1', '5', '0'),
  ('-', 'COPLES ROSCADOS POLIPROPILENO', '"2"""', 'PIEZA', 'Genérico', 'ESTANTE 2', '', 'NUEVO', '1', '3', '0'),
  ('-', '"REDUCCION BUSHING 2""-1 1/2"" PVC C80"', '"2"""', 'PIEZA', 'Genérico', 'ESTANTE 2', '', 'NUEVO', '1', '2', '0'),
  ('-', '"NIPLE 2"" PVC C80"', '"2"""', 'PIEZA', 'Genérico', 'ESTANTE 2', '', 'NUEVO', '1', '2', '0'),
  ('-', '"REDUCCION BUSHING 2""-3/4"" PVC C80"', '"2"""', 'PIEZA', 'Genérico', 'ESTANTE 2', '', 'NUEVO', '1', '1', '0'),
  ('-', '"REDUCCION BUSHING 2""-1"" PVC C80"', '"2"""', 'PIEZA', 'Genérico', 'ESTANTE 2', '', 'NUEVO', '1', '1', '0'),
  ('-', '"REDUCCION BUSHING 2""-1/2"" PVC C80"', '"2"""', 'PIEZA', 'Genérico', 'ESTANTE 2', '', 'NUEVO', '1', '1', '0'),
  ('-', 'TEE ROSCADA PVC C80', '"2"""', 'PIEZA', 'Genérico', 'ESTANTE 2', '', 'NUEVO', '1', '1', '0'),
  ('-', '"COPLE REDUCCION DE 2""-1"" PVC C80"', '"2"""', 'PIEZA', 'Genérico', 'ESTANTE 2', '', 'NUEVO', '1', '1', '0'),
  ('-', 'CODO 90  ROSCADO PVC C80', '"2"""', 'PIEZA', 'Genérico', 'ESTANTE 2', '', 'NUEVO', '1', '1', '0'),
  ('-', 'CODO 90 CEMENTADO PVC C80', '"2"""', 'PIEZA', 'Genérico', 'ESTANTE 2', '', 'NUEVO', '1', '1', '0'),
  ('-', '"NIPLE ROSCADO 1 1/2"" PVC C80 "', '"1 1/2"""', 'PIEZA', 'Genérico', 'ESTANTE 2', '', 'NUEVO', '1', '3', '0'),
  ('-', '"TUERCA UNION 1 1/2"" PVC C80 CEMENTADO"', '"1 1/2"""', 'PIEZA', 'Genérico', 'ESTANTE 2', '', 'NUEVO', '1', '1', '0'),
  ('-', '"COPLE CEMENTADO 1 1/2"" PVC C80"', '"1 1/2"""', 'PIEZA', 'Genérico', 'ESTANTE 2', '', 'NUEVO', '1', '1', '0'),
  ('-', '"REDUCCION BUSHING DE 2""-1"""', '"2"""', 'PIEZA', 'Genérico', 'ESTANTE 2', '', 'NUEVO', '1', '1', '0'),
  ('-', '"CODO 90 1/2"" PVC C80 CEMENTADO"', '"1/2"""', 'PIEZA', 'Genérico', 'ESTANTE 2', '', 'NUEVO', '1', '2', '0'),
  ('-', '"CODO 90 PVC C80 CEMENTADO 1"""', '"1"""', 'PIEZA', 'Genérico', 'ESTANTE 2', '', 'NUEVO', '1', '2', '0'),
  ('-', '"CODO 45 PVC C80 CEMENTADO 1"""', '"1"""', 'PIEZA', 'Genérico', 'ESTANTE 2', '', 'NUEVO', '1', '3', '0'),
  ('-', '"TUERCA UNION PVC C80 CEMENTADA 1"""', '"1"""', 'PIEZA', 'Genérico', 'ESTANTE 2', '', 'NUEVO', '1', '1', '0'),
  ('-', '"TEE PVC C80 CEMENTADA 1"""', '"1"""', 'PIEZA', 'Genérico', 'ESTANTE 2', '', 'NUEVO', '1', '0', '0'),
  ('-', '"COPLE PVC C80 CEMENTADA 1"""', '"1"""', 'PIEZA', 'Genérico', 'ESTANTE 2', '', 'NUEVO', '1', '1', '0'),
  ('-', '"CODO 90 PVC C80 CEMENTADO 3/4"""', '"3/4"""', 'PIEZA', 'Genérico', 'ESTANTE 2', '', 'NUEVO', '1', '5', '0'),
  ('-', '"CODOS 45 PVC C80 CEMENTADO 3/4"""', '"3/4"""', 'PIEZA', 'Genérico', 'ESTANTE 2', '', 'NUEVO', '1', '1', '0'),
  ('-', '"COPLE PVC C80 CEMENTADO 3/4"""', '"3/4"""', 'PIEZA', 'Genérico', 'ESTANTE 2', '', 'NUEVO', '1', '4', '0'),
  ('-', '"TEE 2"" GALVANIZADO"', '"2"""', 'PIEZA', 'Genérico', 'ESTANTE 2', '', 'NUEVO', '1', '2', '0'),
  ('-', '"COPLE 2"" GALVANIZADO"', '"2"""', 'PIEZA', 'Genérico', 'ESTANTE 2', '', 'NUEVO', '1', '3', '0'),
  ('-', '"CODO 45 2"" GALVANIZADO"', '"2"""', 'PIEZA', 'Genérico', 'ESTANTE 2', '', 'NUEVO', '1', '1', '0'),
  ('-', '"TUERCA UNION 1 1/2"" GALVANIZADO"', '"1 1/2"""', 'PIEZA', 'Genérico', 'ESTANTE 2', '', 'NUEVO', '1', '1', '0'),
  ('-', '"CODOS 90 1 1/2"" GALVANIZADO"', '"1 1/2"""', 'PIEZA', 'Genérico', 'ESTANTE 2', '', 'NUEVO', '1', '3', '0'),
  ('-', '"NIPLES 1 1/2"" GALVANIZADO"', '"1 1/2"""', 'PIEZA', 'Genérico', 'ESTANTE 2', '', 'NUEVO', '1', '4', '0'),
  ('-', '"TAPON 1 1/2"" GALVANIZADO"', '"1 1/2"""', 'PIEZA', 'Genérico', 'ESTANTE 2', '', 'NUEVO', '1', '2', '0'),
  ('-', '"NIPLE 2"" GALVANIZADO"', '"2"""', 'PIEZA', 'Genérico', 'ESTANTE 2', '', 'NUEVO', '1', '2', '0'),
  ('-', '"NIPLE BOTELLA2"" GALVANIZADO"', '"2"""', 'PIEZA', 'Genérico', 'ESTANTE 2', '', 'NUEVO', '1', '1', '0'),
  ('-', '"NIPLES 1"" GALVANIZADO"', '"1"""', 'PIEZA', 'Genérico', 'ESTANTE 2', '', 'NUEVO', '1', '23', '0'),
  ('-', '"CODO 90 1"" GALVANIZADO"', '"1"""', 'PIEZA', 'Genérico', 'ESTANTE 2', '', 'NUEVO', '1', '2', '0'),
  ('-', '"CODO PIPA 1"" GALVANIZADO"', '"1"""', 'PIEZA', 'Genérico', 'ESTANTE 2', '', 'NUEVO', '1', '8', '0'),
  ('-', '"CODO REDUCTOR DE 1""-3/4"" GALVANIZADO"', '"1""-3/4"""', 'PIEZA', 'Genérico', 'ESTANTE 2', '', 'NUEVO', '1', '2', '0'),
  ('-', '"COPLES 1"" GALVANIZADO"', '"1"""', 'PIEZA', 'Genérico', 'ESTANTE 2', '', 'NUEVO', '1', '4', '0'),
  ('-', '"COPLE 1"" 300 LIBRAS"', '"1"""', 'PIEZA', 'Genérico', 'ESTANTE 2', '', 'NUEVO', '1', '1', '0'),
  ('-', '"TUERCA UNION 1"" 300 LIBRAS"', '"1"""', 'PIEZA', 'Genérico', 'ESTANTE 2', '', 'NUEVO', '1', '2', '0'),
  ('-', '"TUERECA UNION 1"" GALVANIZADO"', '"1"""', 'PIEZA', 'Genérico', 'ESTANTE 2', '', 'NUEVO', '1', '1', '0'),
  ('-', '"TEE 1"" GALVANIZADO"', '"1"""', 'PIEZA', 'Genérico', 'ESTANTE 2', '', 'NUEVO', '1', '1', '0'),
  ('-', '"TAPON 1"" GALVANIZADO"', '"1"""', 'PIEZA', 'Genérico', 'ESTANTE 2', '', 'NUEVO', '1', '1', '0'),
  ('-', 'CODO 45 300 LIBRAS', '"1"""', 'PIEZA', 'Genérico', 'ESTANTE 2', '', 'NUEVO', '1', '3', '0'),
  ('-', '"CONECTOR FLEER DE 1"" "', '"1"""', 'PIEZA', 'Genérico', 'ESTANTE 2', '', 'NUEVO', '1', '2', '0'),
  ('-', '"REDUCCION BUSHING 2""-3/4"" ACERO INOXIDABLE"', '"2""-3/4"""', 'PIEZA', 'Genérico', 'ESTANTE 2', '', 'NUEVO', '1', '8', '0'),
  ('-', '"REDUCCION BUSHING DE 2""-1"" ACERO INOXIDABLE"', '"2""-1"""', 'PIEZA', 'Genérico', 'ESTANTE 2', '', 'NUEVO', '1', '9', '0'),
  ('-', '"TEE 1"" ACERO INOXIDABLE"', '"1"""', 'PIEZA', 'Genérico', 'ESTANTE 2', '', 'NUEVO', '1', '1', '0'),
  ('-', '"REDUCCION BUSHING DE 1""-1/2"" ACERO INOXIDABLE"', '"1""-1/2"""', 'PIEZA', 'Genérico', 'ESTANTE 2', '', 'NUEVO', '1', '3', '0'),
  ('-', '"REDUCCION BUSHING DE 3/4""-1/2"" ACERO INOXIDABLE"', '"3/42-1/2"""', 'PIEZA', 'Genérico', 'ESTANTE 2', '', 'NUEVO', '1', '1', '0'),
  ('-', '"ESPIGA DE 1/2"" ACERO INOXIDABLE"', '"1/2"""', 'PIEZA', 'Genérico', 'ESTANTE 2', '', 'NUEVO', '1', '1', '0'),
  ('-', '"ESPIGA DE 3/4"" ACERO INOXIDABLE"', '"3/4"""', 'PIEZA', 'Genérico', 'ESTANTE 2', '', 'NUEVO', '1', '4', '0'),
  ('-', '"CODO 90 1"" ACERO INOXIDABLE"', '"1"""', 'PIEZA', 'Genérico', 'ESTANTE 2', '', 'NUEVO', '1', '11', '0'),
  ('-', '"NIPLES 1"" ACERO INOXIDABLE"', '"1"""', 'PIEZA', 'Genérico', 'ESTANTE 2', '', 'NUEVO', '1', '11', '0'),
  ('-', '"CODOS 90 3/4"" ACERO INOXIDABLE"', '"3/4"""', 'PIEZA', 'Genérico', 'ESTANTE 2', '', 'NUEVO', '1', '7', '0'),
  ('-', '"NIPLES 3/4"" ACERO INOXIDABLE"', '"3/4"""', 'PIEZA', 'Genérico', 'ESTANTE 2', '', 'NUEVO', '1', '7', '0'),
  ('-', '"FILTRO EN Y 3/4"" ACERO INOXIDABLE"', '"3/4"""', 'PIEZA', 'Genérico', 'ESTANTE 2', '', 'NUEVO', '1', '2', '0'),
  ('-', 'ADAPTADOR BSP A NPT', '"1"""', 'PIEZA', 'PIUSI', 'ESTANTE 2', '', 'NUEVO', '1', '1', '0'),
  ('-', '"CODO 90 3/4"" GALVANIZADO"', '"3/4"""', 'PIEZA', 'Genérico', 'ESTANTE 2', '', 'NUEVO', '1', '10', '0'),
  ('-', '"CODO REDUCTOR DE 3/4""-1/2"" GALVANIZADO"', '"3/4""-1/2"""', 'PIEZA', 'Genérico', 'ESTANTE 2', '', 'NUEVO', '1', '4', '0'),
  ('-', '"COPLES 3/4"" GALVANZADO"', '"3/4"""', 'PIEZA', 'Genérico', 'ESTANTE 2', '', 'NUEVO', '1', '7', '0'),
  ('-', '"CODO 45 3/4"" 150 LIBRAS"', '"3/4"""', 'PIEZA', 'Genérico', 'ESTANTE 2', '', 'NUEVO', '1', '5', '0'),
  ('-', '"CODO 90 3/4"" 150 LIBRAS"', '"3/4"""', 'PIEZA', 'Genérico', 'ESTANTE 2', '', 'NUEVO', '1', '5', '0'),
  ('-', '"TUERCA UNION 3/4"" GALVANIZADO"', '"3/4"""', 'PIEZA', 'Genérico', 'ESTANTE 2', '', 'NUEVO', '1', '3', '0'),
  ('-', 'NIPLES 3/4 GALVANIZADO', '"3/4"""', 'PIEZA', 'Genérico', 'ESTANTE 2', '', 'NUEVO', '1', '6', '0'),
  ('-', '"TAPONES 3/4"" GALVANIZADO"', '"3/4"""', 'PIEZA', 'Genérico', 'ESTANTE 2', '', 'NUEVO', '1', '5', '0'),
  ('-', '"TEE 3/4"" 150 LIBRAS"', '"3/4"""', 'PIEZA', 'Genérico', 'ESTANTE 2', '', 'NUEVO', '1', '2', '0'),
  ('-', '"COPLES 3/4"" 150 LIBRAS"', '"3/4"""', 'PIEZA', 'Genérico', 'ESTANTE 2', '', 'NUEVO', '1', '3', '0'),
  ('-', '"CONECTORES FLEER 3/4"""', '"3/4"""', 'PIEZA', 'Genérico', 'ESTANTE 2', '', 'NUEVO', '1', '3', '0'),
  ('-', '"TEE 3/4"" GALVANIZADO"', '"3/4"""', 'PIEZA', 'Genérico', 'ESTANTE 2', '', 'NUEVO', '1', '1', '0'),
  ('-', '"TEE 3/4"" 300 LIBRAS"', '"3/4"""', 'PIEZA', 'Genérico', 'ESTANTE 2', '', 'NUEVO', '1', '4', '0'),
  ('-', '"CODOS 90 3/4"" 300 LIBRAS"', '"3/4"""', 'PIEZA', 'Genérico', 'ESTANTE 2', '', 'NUEVO', '1', '14', '0'),
  ('-', '"TUERCA UNION 3/4"" 300 LIBRAS"', '"3/4"""', 'PIEZA', 'Genérico', 'ESTANTE 2', '', 'NUEVO', '1', '4', '0'),
  ('-', '"COPLES 3/4"" 300 LIBRAS"', '"3/4"""', 'PIEZA', 'Genérico', 'ESTANTE 2', '', 'NUEVO', '1', '2', '0'),
  ('-', '"CODO CON CUERDA DE AMBOS EXTREMOS 3/4"" "', '"3/4"""', 'PIEZA', 'Genérico', 'ESTANTE 2', '', 'NUEVO', '1', '1', '0'),
  ('-', '"NIPLES DE 1/2"" 300 LIBRAS"', '"1/2"""', 'PIEZA', 'Genérico', 'ESTANTE 2', '', 'NUEVO', '1', '8', '0'),
  ('-', '"CONECTOR FLEER 1/2"""', '', 'PIEZA', 'Genérico', 'ESTANTE 2', '', 'NUEVO', '1', '4', '0'),
  ('-', '"TEE 1/2"" 300 LIBRAS"', '', 'PIEZA', 'Genérico', 'ESTANTE 2', '', 'NUEVO', '1', '1', '0'),
  ('-', '"TUERCA UNION 1/2"" 300 LIBRAS"', '', 'PIEZA', 'Genérico', 'ESTANTE 2', '', 'NUEVO', '1', '1', '0'),
  ('-', '"CONECTOR RAPIDO HERMBRA 1/2"""', '', 'PIEZA', 'Genérico', 'ESTANTE 2', '', 'NUEVO', '1', '1', '0'),
  ('-', '"COPLE DE 1/2"" 300 LIBRAS"', '', 'PIEZA', 'Genérico', 'ESTANTE 2', '', 'NUEVO', '1', '1', '0'),
  ('-', '"REDUCCION BUSHING DE 2"" A 1 1/2"""', '"2""-1 1/2"""', 'PIEZA', 'Genérico', 'ESTANTE 2', '', 'NUEVO', '1', '3', '0'),
  ('-', '"REDUCCION BUSHING DE 2"" A 1"""', '"2""-1"""', 'PIEZA', 'Genérico', 'ESTANTE 2', '', 'NUEVO', '1', '7', '0'),
  ('-', '"REDUCCION BUSHING DE 2"" A 3/4"""', '"2""-3/4"""', 'PIEZA', 'Genérico', 'ESTANTE 2', '', 'NUEVO', '1', '6', '0'),
  ('-', '"REDUCCION BUSHING DE 1"" A 3/4"""', '"1""-3/4"""', 'PIEZA', 'Genérico', 'ESTANTE 2', '', 'NUEVO', '1', '12', '0'),
  ('-', '"REDUCCION BUSHING DE 1"" A 1/2"""', '"1""-1/2"""', 'PIEZA', 'Genérico', 'ESTANTE 2', '', 'NUEVO', '1', '5', '0'),
  ('-', '"REDUCCION BUSHING DE 3/4"" A 1/2"" "', '"3/4""-1/2"""', 'PIEZA', 'Genérico', 'ESTANTE 2', '', 'NUEVO', '1', '33', '0'),
  ('-', '"REDUCCION BUSHING DE 1/2"" A 3/8"""', '"1/2""-3/8"""', 'PIEZA', 'Genérico', 'ESTANTE 2', '', 'NUEVO', '1', '11', '0'),
  ('-', '"REDUCCION BUSHING DE 1/2"" A 1/4"""', '"1/2""-1/4"""', 'PIEZA', 'Genérico', 'ESTANTE 2', '', 'NUEVO', '1', '13', '0'),
  ('-', '"REDUCCION BUSHING DE 3/4"" A 3/8"""', '"3/4""-3/8"""', 'PIEZA', 'Genérico', 'ESTANTE 2', '', 'NUEVO', '1', '3', '0'),
  ('-', '"REDUCCION BUSHING DE 3/8"" A 1/4"""', '"3/8""-1/4"""', 'PIEZA', 'Genérico', 'ESTANTE 2', '', 'NUEVO', '1', '8', '0'),
  ('-', '"REDUCCION CAMPANA DE 1/2"" A 1/4"""', '"1/2""-1/4"""', 'PIEZA', 'Genérico', 'ESTANTE 2', '', 'NUEVO', '1', '4', '0'),
  ('-', '"REDUCCION CAMPANA DE 1/2"" A 3/8"""', '"1/2""-3/8"""', 'PIEZA', 'Genérico', 'ESTANTE 2', '', 'NUEVO', '1', '5', '0'),
  ('-', '"NIPLE BOTELLA 3/4"" GALVANIZADO"', '"3/4"""', 'PIEZA', 'Genérico', 'ESTANTE 2', '', 'NUEVO', '1', '13', '0'),
  ('-', '"NIPLE BOTELLA 1"" GALVANIZADO"', '"1"""', 'PIEZA', 'Genérico', 'ESTANTE 2', '', 'NUEVO', '1', '4', '0'),
  ('-', '"ESPIGA PVC C80 1 1/2"""', '"1 1/2"""', 'PIEZA', 'Genérico', 'ESTANTE 2', '', 'NUEVO', '1', '2', '0'),
  ('-', '"ESPIGA PVC C80 1"""', '"1"""', 'PIEZA', 'Genérico', 'ESTANTE 2', '', 'NUEVO', '1', '7', '0'),
  ('-', '"ESPIGA PVC C80 3/4"""', '"3/4"""', 'PIEZA', 'Genérico', 'ESTANTE 2', '', 'NUEVO', '1', '4', '0'),
  ('-', '"ESPIGA DE LATON 3/4"""', '"3/4"""', 'PIEZA', 'Genérico', 'ESTANTE 2', '', 'NUEVO', '1', '4', '0'),
  ('-', '"ESPIGA DE LATON 1"""', '"1"""', 'PIEZA', 'Genérico', 'ESTANTE 2', '', 'NUEVO', '1', '1', '0'),
  ('-', '"ESPIGA DE LATON 1/2"""', '"1/2"""', 'PIEZA', 'Genérico', 'ESTANTE 2', '', 'NUEVO', '1', '1', '0'),
  ('-', '"NIPLE BOTELLA DE 1/2"" GALVANIZADO"', '"1/2"""', 'PIEZA', 'Genérico', 'ESTANTE 2', '', 'NUEVO', '1', '1', '0'),
  ('-', '"TRIPLE ESPIGA PVC C80 3/4"""', '"3/4"""', 'PIEZA', 'Genérico', 'ESTANTE 2', '', 'NUEVO', '1', '1', '0'),
  ('-', 'VALVULAS', '', 'PIEZA', 'Genérico', 'ESTANTE 2', '', 'NUEVO', '1', '0', '0'),
  ('-', '"VALUVULAS 1"""', '"1"""', 'PIEZA', 'Genérico', 'ESTANTE 2', '', 'NUEVO', '1', '2', '0'),
  ('-', '"VALVULAS ALTA PRESION 1/2"""', '"1/2"""', 'PIEZA', 'Genérico', 'ESTANTE 2', '', 'NUEVO', '1', '2', '0'),
  ('-', '"VALVULA PVC C80 1/2"""', '"1/2"""', 'PIEZA', 'Genérico', 'ESTANTE 2', '', 'NUEVO', '1', '1', '0'),
  ('-', '"VALVULA DE 1/2"""', '"1/2"""', 'PIEZA', 'Genérico', 'ESTANTE 2', '', 'NUEVO', '1', '2', '0'),
  ('-', '"VALVULAS DE 3/8"" LATON "', '"3/8"""', 'PIEZA', 'Genérico', 'ESTANTE 2', '', 'NUEVO', '1', '2', '0'),
  ('-', '"VALVULA DE 3/4"" LATON "', '"3/4"""', 'PIEZA', 'Genérico', 'ESTANTE 2', '', 'NUEVO', '1', '1', '0'),
  ('-', '"VALUVULA DE 1/2"" NEGRAS"', '"1/2"""', 'PIEZA', 'Genérico', 'ESTANTE 2', '', 'NUEVO', '1', '4', '0'),
  ('-', '"NIPLE CUERDA CORRIDA 1"" PVC C80"', '"1"""', 'PIEZA', 'Genérico', 'ESTANTE 2', '', 'NUEVO', '1', '5', '0'),
  ('-', '"COPLE ROSCADO A CEMENTADO 3/4"" PVC C80"', '"3/4"""', 'PIEZA', 'Genérico', 'ESTANTE 2', '', 'NUEVO', '1', '4', '0'),
  ('-', '"COPLE ROSCADO A CEMENTADO 1/2"" PVC C80"', '"1/2"""', 'PIEZA', 'Genérico', 'ESTANTE 2', '', 'NUEVO', '1', '4', '0'),
  ('-', '"COPLE ROSCADO 1"" PVC C80"', '"1"""', 'PIEZA', 'Genérico', 'ESTANTE 2', '', 'NUEVO', '1', '2', '0'),
  ('-', '"CODO 90 ROSCADO  3/4"" PVC C80"', '"3/4"""', 'PIEZA', 'Genérico', 'ESTANTE 2', '', 'NUEVO', '1', '2', '0'),
  ('-', '"NIPLE ROSCADO 3/4"" PVC C80"', '"3/4"""', 'PIEZA', 'Genérico', 'ESTANTE 2', '', 'NUEVO', '1', '4', '0'),
  ('-', '"REDUCCION BUSHING 3/4"" A 1/2"""', '"3/4""- 1/2"""', 'PIEZA', 'Genérico', 'ESTANTE 2', '', 'NUEVO', '1', '3', '0'),
  ('-', '"ESPIGA 3/4"" PVC C80"', '"3/4"""', 'PIEZA', 'Genérico', 'ESTANTE 2', '', 'NUEVO', '1', '2', '0'),
  ('-', '"NIPLE CUERDA CORRIDA 1/2""  PVC C80"', '"1/2"""', 'PIEZA', 'Genérico', 'ESTANTE 2', '', 'NUEVO', '1', '3', '0'),
  ('-', '"CODO 90 ROSCADO 1/2"" PVC C80"', '"1/2"""', 'PIEZA', 'Genérico', 'ESTANTE 2', '', 'NUEVO', '1', '1', '0'),
  ('-', '"CODO 90 ROSCADO 1"" PVC C80"', '"1"""', 'PIEZA', 'Genérico', 'ESTANTE 2', '', 'NUEVO', '1', '1', '0'),
  ('-', '"ADAPTADOR MACHO CEMENTADO 1/2"" PVC C80"', '"1/2"""', 'PIEZA', 'Genérico', 'ESTANTE 2', '', 'NUEVO', '1', '1', '0'),
  ('-', '"CODO 1"" PARA EQUIPO UREA PIUSI "', '"1"""', 'PIEZA', 'PIUSI', 'ESTANTE 2', '', 'USADO', '1', '1', '0'),
  ('-', '"ESPIGA 1"" PARA EQUIPO UREA PIUSI"', '"1"""', 'PIEZA', 'PIUSI', 'ESTANTE 2', '', 'USADO', '1', '1', '0'),
  ('-', '"FILTRO EN Y 1"" LATON "', '"1"""', 'PIEZA', 'FOSET', 'ESTANTE 2', '', 'NUEVO', '1', '3', '0'),
  ('-', '"FILTRO EN Y 3/4"" LATON "', '"3/4"""', 'PIEZA', 'FOSET', 'ESTANTE 2', '', 'NUEVO', '1', '3', '0'),
  ('-', '"FILTRO EN Y 1/2"" DE LATON "', '"1/2"""', 'PIEZA', 'FOSET', 'ESTANTE 2', '', 'NUEVO', '1', '2', '0'),
  ('L 5315', '"CEDAZO FILTRO DE POLIPROPILENO 1"""', '"1"""', 'PIEZA', 'WINTEK', 'ESTANTE 2', '', 'USADO', '1', '3', '0'),
  ('-', '"PICHANCHA 1"""', '"1"""', 'PIEZA', 'Genérico', 'ESTANTE 2', '', 'NUEVO', '1', '1', '0'),
  ('-', '"PICHANCHA 3/4"" LATON "', '"3/4"""', 'PIEZA', 'Genérico', 'ESTANTE 2', '', 'NUEVO', '1', '1', '0'),
  ('-', '"PICHANCHA 1/2"" LATON "', '"1/2"""', 'PIEZA', 'Genérico', 'ESTANTE 2', '', 'NUEVO', '1', '1', '0'),
  ('-', '"RESPIRADEROS PARA TOTTE 2"""', '"2"""', 'PIEZA', 'Genérico', 'ESTANTE 2', '', 'USADO', '1', '3', '0'),
  ('-', '"ABRAZADERA PARA UNICANAL  1"""', '"1"""', 'PIEZA', 'Genérico', 'ESTANTE 2', '', 'NUEVO', '1', '22', '0'),
  ('-', '"ABRAZADERA PARA UNICANAL  3/4"""', '"3/4"""', 'PIEZA', 'Genérico', 'ESTANTE 2', '', 'NUEVO', '1', '33', '0'),
  ('-', '"ABRAZADERA PARA UNICANAL 1/2"""', '"1/2"""', 'PIEZA', 'Genérico', 'ESTANTE 2', '', 'NUEVO', '1', '34', '0'),
  ('-', 'ESPIGAS PARA AIRE', '', 'PIEZA', 'Genérico', 'SIN ASIGNAR', '', 'NUEVO', '1', '0', '0'),
  ('-', '"ESPIGAS PARA AIRE 3/8""-  3/8"""', '"3/8""- 3/8"""', 'PIEZA', 'Genérico', 'ESTANTE 2', '', 'NUEVO', '1', '37', '0'),
  ('-', '"ESPIGAS PARA AIRE  3/8""- 1/4"""', '"3/8""- 1/4"""', 'PIEZA', 'Genérico', 'ESTANTE 2', '', 'NUEVO', '1', '11', '0'),
  ('-', '"ESPIGAS PARA AIRE 1/4""- 1/4"""', '"1/4""- 1/4"""', 'PIEZA', 'Genérico', 'ESTANTE 2', '', 'NUEVO', '1', '29', '0'),
  ('-', 'CONECTOR RAPIDO PARA AIRE', '', 'PIEZA', 'Genérico', 'SIN ASIGNAR', '', 'NUEVO', '1', '0', '0'),
  ('-', '"COPLE RAPIDO HEMBRA  1/4"""', '"1/4"""', 'PIEZA', 'Genérico', 'ESTANTE 2', '', 'NUEVO', '1', '5', '0'),
  ('-', '"CONECTOR MACHO 1/4"" NPT "', '"1/4"""', 'PIEZA', 'Genérico', 'ESTANTE 2', '', 'NUEVO', '1', '2', '0'),
  ('-', '"VALVULAS TIPO MARIPOSA  PARA AIRE 1/4"""', '"1/4"""', 'PIEZA', 'Genérico', 'ESTANTE 2', '', 'NUEVO', '1', '8', '0'),
  ('-', '"CONEXIONES 1/4"" "', '', 'PIEZA', 'Genérico', 'ESTANTE 2', '', 'NUEVO', '1', '0', '0'),
  ('-', '"NIPLES 1/4"" GALVANIZADO"', '"1/4"""', 'PIEZA', 'Genérico', 'ESTANTE 2', '', 'NUEVO', '1', '21', '0'),
  ('-', '"CODO 90 1/4"" GALVANIZADO"', '"1/4"""', 'PIEZA', 'Genérico', 'ESTANTE 2', '', 'NUEVO', '1', '11', '0'),
  ('-', '"CODO 3/8"" GALVANIZADO "', '"3/8"""', 'PIEZA', 'Genérico', 'ESTANTE 2', '', 'NUEVO', '1', '2', '0'),
  ('-', 'ABRAZADERA  SIN FIN', '', 'PIEZA', 'Genérico', 'SIN ASIGNAR', '', 'NUEVO', '1', '0', '0'),
  ('-', 'ABRAZADERA SIN FIN DIFERENTE MEDIDA', '', 'PIEZA', 'Genérico', 'ESTANTE 2', '', 'NUEVO', '1', '42', '0'),
  ('-', '"ABRAZADERA SIN FIN 1/4"""', '"1/4"""', 'PIEZA', 'Genérico', 'ESTANTE 2', '', 'NUEVO', '1', '65', '0'),
  ('-', '"CONECTORES PARA MANGUERA DE NYLON 1/4"""', '', 'PIEZA', 'Genérico', 'SIN ASIGNAR', '', 'NUEVO', '1', '0', '0'),
  ('-', '"CONECTOR CODO 1/4"" - 3/8"" NPT"', '"1/4""- 3/8"""', 'PIEZA', 'Genérico', 'ESTANTE 2', '', 'NUEVO', '1', '4', '0'),
  ('-', '"CONECTOR CODO 1/4"" - 1/4"" NPT"', '"1/4""- 1/4"""', 'PIEZA', 'Genérico', 'ESTANTE 2', '', 'NUEVO', '1', '6', '0'),
  ('-', '"CONECTOR RECTO 1/4"" - 1/4"" NPT"', '"1/4""- 1/4"""', 'PIEZA', 'Genérico', 'ESTANTE 2', '', 'NUEVO', '1', '16', '0'),
  ('-', 'ABRAZADERA TIPO U DIFERENTES MEDIDAS', '', 'PIEZA', 'Genérico', 'ESTANTE 2', '', 'NUEVO', '1', '35', '0'),
  ('-', '"ROLLO DE MANGUERA 3/8"""', '', 'Metro', 'PARKER', 'ESTANTE 2', '', 'NUEVO', '1', '0', '0'),
  ('L5306', 'CHAROLA ANTI-GOTEO', '', 'PIEZA', 'WINTEK', 'ESTANTE 2', '', 'NUEVO', '1', '1', '1050'),
  ('-', 'PAQUETE DE CINCHOS DIFERENTES LARGOS', '', 'PIEZA', 'Genérico', 'ESTANTE 2', '', 'NUEVO', '1', '19', '0'),
  ('-', '"MANGUERA DE NYLON 1/4"""', '"1/4"""', 'Metro', 'PISCIS', 'ESTANTE 2', '', 'NUEVO', '1', '3', '0'),
  ('-', '"TUBO 3/4"" GALVANIZADO"', '"3/4"""', 'Metro', 'Genérico', 'SIN ASIGNAR', '', 'NUEVO', '1', '10', '0'),
  ('-', '"TUBO 1/2"" GALVANIZADO "', '"1/2"""', 'Metro', 'Genérico', 'SIN ASIGNAR', '', 'NUEVO', '1', '4', '0'),
  ('-', '"TUBO 1"" ACERO C40"', '"1"""', 'Metro', 'Genérico', 'SIN ASIGNAR', '', 'NUEVO', '1', '1', '0'),
  ('-', '"TUBO ACERO 3/4"" C 40"', '"3/4"""', 'Metro', 'Genérico', 'SIN ASIGNAR', '', 'NUEVO', '1', '11.58', '0'),
  ('-', '"TUBO DE ACERO 1/2"" C40"', '"1/2"""', 'Metro', 'Genérico', 'SIN ASIGNAR', '', 'NUEVO', '1', '4.6', '0'),
  ('-', 'MENSULAS', '', 'PIEZA', 'Genérico', 'SIN ASIGNAR', '', 'NUEVO', '1', '7', '0'),
  ('-', 'PERFILES NEGROS', '', 'Metro', 'Genérico', 'SIN ASIGNAR', '', 'NUEVO', '1', '1.5', '0'),
  ('-', 'PERFILES GRIS', '', 'Metro', 'Genérico', 'SIN ASIGNAR', '', 'NUEVO', '1', '1.5', '0'),
  ('-', '"ANGULO DE ALUMINIO 3/4"""', '"3/4"""', 'Metro', 'Genérico', 'SIN ASIGNAR', '', 'NUEVO', '1', '11', '0'),
  ('-', '"TUBO CONDUIT PARA PARED DELGADA D 1/2"""', '"1/2"""', 'Metro', 'Genérico', 'SIN ASIGNAR', '', 'NUEVO', '1', '23.66', '0'),
  ('-', '"CONDUIT ELECTRICO PVC 1/2"""', '"1/2"""', 'Metro', 'Genérico', 'SIN ASIGNAR', '', 'NUEVO', '1', '6', '0'),
  ('-', 'ESPARRAGOS', '', 'Metro', 'Genérico', 'SIN ASIGNAR', '', 'NUEVO', '1', '9', '0'),
  ('-', 'ESPARRAGO DELGADO', '', 'Metro', 'Genérico', 'SIN ASIGNAR', '', 'NUEVO', '1', '2.2', '0'),
  ('-', '"TUBO COBRE DE 1/2"""', '"1/2"""', 'Metro', 'Genérico', 'SIN ASIGNAR', '', 'NUEVO', '1', '4', '0'),
  ('-', 'VARILLA', '', 'Metro', 'Genérico', 'SIN ASIGNAR', '', 'NUEVO', '1', '1.3', '0'),
  ('-', 'UNICANAL', '2X2', 'Metro', 'Genérico', 'SIN ASIGNAR', '', 'NUEVO', '1', '3.5', '0'),
  ('-', '"TUBO PVC  C80 1/2"""', '"1/2"""', 'Metro', 'Genérico', 'SIN ASIGNAR', '', 'NUEVO', '1', '2.7', '0'),
  ('-', 'TUBERIA NEGRA', '', 'Metro', 'Genérico', 'SIN ASIGNAR', '', 'NUEVO', '1', '9', '0'),
  ('-', '"TUBO PVC C80 2"""', '"2"""', 'Metro', 'Genérico', 'SIN ASIGNAR', '', 'NUEVO', '1', '5', '0'),
  ('-', '"TUBO PVC C80 3/4"""', '"3/4"""', 'Metro', 'Genérico', 'SIN ASIGNAR', '', 'NUEVO', '1', '8', '0'),
  ('-', '"TUBO PVC C80 1"""', '"1"""', 'Metro', 'Genérico', 'SIN ASIGNAR', '', 'NUEVO', '1', '3', '0'),
  ('-', '"TUBO PVC C80 1 1/2"""', '"1 1/2"""', 'Metro', 'Genérico', 'SIN ASIGNAR', '', 'NUEVO', '1', '0.6', '0'),
  ('-', '"TUBO PVC C40 1 1/2"""', '"1 1/2"""', 'Metro', 'Genérico', 'SIN ASIGNAR', '', 'NUEVO', '1', '2.1', '0'),
  ('-', '"TUBO PVC C40 1"""', '"1"""', 'Metro', 'Genérico', 'SIN ASIGNAR', '', 'NUEVO', '1', '11', '0'),
  ('-', '"TUBO PVC C40 1/2"""', '"1/2"""', 'Metro', 'Genérico', 'SIN ASIGNAR', '', 'NUEVO', '1', '5', '0'),
  ('-', '"TUBO PVC C40 1/2"""', '"1/2"""', 'Metro', 'Genérico', 'SIN ASIGNAR', '', 'NUEVO', '1', '2', '0'),
  ('-', '"SOLERA DE 1"""', '"1"""', 'Metro', 'Genérico', 'SIN ASIGNAR', '', 'NUEVO', '1', '1', '0'),
  ('-', 'MOLDURA DE UNION DE POLICARBONATO', '', 'Metro', 'Genérico', 'SIN ASIGNAR', '', 'NUEVO', '1', '2.8', '0')
) AS v(modelo, descripcion, medida, udm, marca, almacen, fila, condicion, stock_min, cantidad, precio);